DROP TABLE JERARQUIA_CUENTAS_VERTICAL IF EXISTS;
CREATE TABLE JERARQUIA_CUENTAS_VERTICAL
AS
SELECT 
    1 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_1 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_1 AS CUENTAS
ON CUENTAS.NODO_GRUPO_1 = GRUPOS.NODO
UNION ALL
SELECT 
    2 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_2 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_2 AS CUENTAS
ON CUENTAS.NODO_GRUPO_2 = GRUPOS.NODO
UNION ALL 
SELECT 
    3 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_3 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_3 AS CUENTAS
ON CUENTAS.NODO_GRUPO_3 = GRUPOS.NODO
UNION ALL 
SELECT 
    4 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_4 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_4 AS CUENTAS
ON CUENTAS.NODO_GRUPO_4 = GRUPOS.NODO
UNION ALL 
SELECT 
    5 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_5 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_5 AS CUENTAS
ON CUENTAS.NODO_GRUPO_5 = GRUPOS.NODO
UNION ALL 
SELECT 
    6 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_6 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_6 AS CUENTAS
ON CUENTAS.NODO_GRUPO_6 = GRUPOS.NODO
UNION ALL 
SELECT 
    7 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_7 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_7 AS CUENTAS
ON CUENTAS.NODO_GRUPO_7 = GRUPOS.NODO
UNION ALL 
SELECT 
    8 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_8 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_8 AS CUENTAS
ON CUENTAS.NODO_GRUPO_8 = GRUPOS.NODO
UNION ALL 
SELECT 
    9 AS NIVEL,
    GRUPOS.NODO,
    GRUPOS.GRUPO,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO
FROM ESQUEMA_GRUPOS_9 AS GRUPOS
INNER JOIN ESQUEMA_CUENTAS_9 AS CUENTAS
ON CUENTAS.NODO_GRUPO_9 = GRUPOS.NODO
DISTRIBUTE ON (CUENTA,NODO);
ALTER TABLE JERARQUIA_CUENTAS_VERTICAL
ORGANIZE ON (NODO);