----------------------------------
---- CREAMOS TABLA DE GRUPOS 1----
----------------------------------
DROP TABLE ESQUEMA_GRUPOS_1 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_1(
    INDICE INT NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
)
DISTRIBUTE ON (NODO);
----------------------------------
---- CREAMOS TABLA DE GRUPOS 2----
----------------------------------
DROP TABLE ESQUEMA_GRUPOS_2 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_2(
    INDICE INT NOT NULL,
    NODO_GRUPO_1 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
) 
DISTRIBUTE ON (NODO);
-----------------------------------
---- CREAMOS TABLA DE GRUPOS 3----
-----------------------------------
DROP TABLE ESQUEMA_GRUPOS_3 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_3(
    INDICE INT NOT NULL,
    NODO_GRUPO_2 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
) 
DISTRIBUTE ON (NODO);
-----------------------------------
---- CREAMOS TABLA DE GRUPOS 4 ----
-----------------------------------
DROP TABLE ESQUEMA_GRUPOS_4 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_4(
    INDICE INT NOT NULL,
    NODO_GRUPO_3 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
) 
DISTRIBUTE ON (NODO);
-----------------------------------
---- CREAMOS TABLA DE GRUPOS 5 ----
-----------------------------------
DROP TABLE ESQUEMA_GRUPOS_5 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_5(
    INDICE INT NOT NULL,
    NODO_GRUPO_4 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
)
DISTRIBUTE ON (NODO);
-----------------------------------
---- CREAMOS TABLA DE GRUPOS 6 ----
-----------------------------------
DROP TABLE ESQUEMA_GRUPOS_6 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_6(
    INDICE INT NOT NULL,
    NODO_GRUPO_5 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
)
DISTRIBUTE ON (NODO);
------------------------------------
---- CREAMOS TABLA DE GRUPOS 7 ----
------------------------------------
DROP TABLE ESQUEMA_GRUPOS_7 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_7(
    INDICE INT NOT NULL,
    NODO_GRUPO_6 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
)
DISTRIBUTE ON (NODO);
------------------------------------
---- CREAMOS TABLA DE GRUPOS 8 ----
------------------------------------
DROP TABLE ESQUEMA_GRUPOS_8 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_8(
    INDICE INT NOT NULL,
    NODO_GRUPO_7 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
)
DISTRIBUTE ON (NODO);
------------------------------------
---- CREAMOS TABLA DE GRUPOS 9 ----
------------------------------------
DROP TABLE ESQUEMA_GRUPOS_9 IF EXISTS;
CREATE TABLE ESQUEMA_GRUPOS_9(
    INDICE INT NOT NULL,
    NODO_GRUPO_8 NCHAR(8) NOT NULL,
    NODO NCHAR(8) NOT NULL,
    SUPERCONCEPTO VARCHAR(256) NOT NULL
) 
DISTRIBUTE ON  (NODO);

