-----------------------------------------------------
---------RECREAMOS BSEG EN BASE A LA TABLA MADRE-----
-----------------------------------------------------
DROP TABLE BSEG_5200 IF EXISTS;
CREATE TABLE BSEG_5200
AS
SELECT 
  BUKRS AS SOCIEDAD,
  KOSTL AS CECO,
  CAST(BLDAT AS DATE) AS FECHA_DOCUMENTO,
  CAST(BUDAT AS DATE) AS FECHA_BASE,
  SGTXT AS TEXTO,
  HKONT AS CUENTA,
  BLART AS TIPO_DOCUMENTO,
  CAST(DMBTR DOUBLE PRECISION) AS IMPORTE_BASE,
  CAST(WRBTR DOUBLE PRECISION) AS IMPORTE_DOCUMENTO,
  PSWSL AS MONEDA_DOCUMENTO,
  PRCTR AS CEBE,
  LIFNR AS NUMERO_PROVEEDOR,
  KUNNR AS NUMERO_CLIENTE,
  PROJK AS NUMERO_pedido,
  DBBLG AS REFERENCIA,
  ZUONR AS ASIGNACION,
  SHKZG AS TIPO_SALDO,
  BELNR AS NUMERO_DOCUMENTO
FROM INPUT_BSEG_5200
DISTRIBUTE ON RANDOM;
--ORGANIZAMOS EN BASE A CUENTAS Y FECHAS
ALTER TABLE BSEG_5200
ORGANIZE ON (CUENTA,FECHA_BASE);
