CREATE TABLE PREINFORME 
AS 
SELECT
    JERARQUIA.NODO, 
    JERARQUIA.GRUPO, 
    JERARQUIA.CUENTA, 
    JERARQUIA.CONCEPTO,
    SALDOS.IMPORTE
FROM JERARQUIA_CUENTAS_VERTICAL AS JERARQUIA 
LEFT JOIN SALDOS_CUENTAS_5200 AS SALDOS 
ON SALDOS.CUENTA = JERARQUIA.CUENTA 
WHERE NODO IN('50050000','50100000','50250000','50350000','50400000','50450000','50500000','50600000','51000000','50850000','50900000')

SELECT NODO, SUM(IMPORTE) AS IMPORTE FROM INFORME GROUP BY NODO

DROP TABLE INFORME IF EXISTS;
CREATE TABLE INFORME
AS
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, CASE WHEN IMPORTE IS NULL THEN 0 ELSE(IMPORTE*-1) END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50050000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, CASE WHEN IMPORTE IS NULL THEN 0 ELSE(IMPORTE*-1) END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50100000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, CASE WHEN IMPORTE IS NULL THEN 0 ELSE(IMPORTE*-1) END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50250000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, CASE WHEN IMPORTE IS NULL THEN 0 ELSE(IMPORTE*-1) END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50350000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, CASE WHEN IMPORTE IS NULL THEN 0 ELSE(IMPORTE*-1) END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50400000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, CASE WHEN IMPORTE IS NULL THEN 0 ELSE(IMPORTE*-1) END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50450000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, WHEN IMPORTE IS NULL THEN 0 ELSE IMPORTE END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50500000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, WHEN IMPORTE IS NULL THEN 0 ELSE IMPORTE END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50600000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, WHEN IMPORTE IS NULL THEN 0 ELSE IMPORTE END AS IMPORTE
FROM PREINFORME
WHERE NODO = '51000000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, WHEN IMPORTE IS NULL THEN 0 ELSE IMPORTE END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50850000'
UNION ALL
SELECT
	NODO,GRUPO,CUENTA,CONCEPTO, WHEN IMPORTE IS NULL THEN 0 ELSE IMPORTE END AS IMPORTE
FROM PREINFORME
WHERE NODO = '50900000'
DISTRIBUTE ON(CUENTA,NODO);