DROP TABLE EJEMPLOS IF EXISTS;
CREATE TABLE EJEMPLOS
AS
SELECT 
    GRUPOS.ID AS ID,
    GRUPOS.SUPERCONCEPTO AS SUPERCONCEPTO,
    CUENTAS.CUENTA AS CUENTA,
    CUENTAS.CONCEPTO,
    CUENTAS.IMPORTE
FROM GRUPOS_9 AS GRUPOS
INNER JOIN IMPORTES_CUENTAS_BSEG_5200_9 AS CUENTAS
ON CUENTAS.ID_GRUPO_9 = GRUPOS.ID
WHERE GRUPOS.ID IN ('50050000','50100000')
--------------------------------------------------------
UNION ALL
--------------------------------------------------------
SELECT 
    GRUPOS.ID AS ID,
    GRUPOS.SUPERCONCEPTO AS SUPERCONCEPTO,
    CUENTAS.CUENTA AS CUENTA,
    CUENTAS.CONCEPTO,
    CUENTAS.IMPORTE
FROM GRUPOS_8 AS GRUPOS
INNER JOIN IMPORTES_CUENTAS_BSEG_5200_8 AS CUENTAS
ON CUENTAS.ID_GRUPO_8 = GRUPOS.ID
WHERE GRUPOS.ID IN ('50250000')
--------------------------------------------------------
UNION ALL
--------------------------------------------------------
SELECT 
    GRUPOS.ID AS ID,
    GRUPOS.SUPERCONCEPTO AS SUPERCONCEPTO,
    CUENTAS.CUENTA AS CUENTA,
    CUENTAS.CONCEPTO,
    CUENTAS.IMPORTE
FROM GRUPOS_7 AS GRUPOS

INNER JOIN IMPORTES_CUENTAS_BSEG_5200_7 AS CUENTAS
ON CUENTAS.ID_GRUPO_7 = GRUPOS.ID
WHERE GRUPOS.ID IN ('50350000','50400000','50450000','50500000')
--------------------------------------------------------
UNION ALL
--------------------------------------------------------
SELECT 
    GRUPOS.ID AS ID,
    GRUPOS.SUPERCONCEPTO AS SUPERCONCEPTO,
    CUENTAS.CUENTA AS CUENTA,
    CUENTAS.CONCEPTO,
    CUENTAS.IMPORTE
FROM GRUPOS_6 AS GRUPOS
INNER JOIN IMPORTES_CUENTAS_BSEG_5200_6 AS CUENTAS
ON CUENTAS.ID_GRUPO_6 = GRUPOS.ID
WHERE GRUPOS.ID IN ('50600000')
--------------------------------------------------------
UNION ALL
--------------------------------------------------------
SELECT 
    GRUPOS.ID AS ID,
    GRUPOS.SUPERCONCEPTO AS SUPERCONCEPTO,
    CUENTAS.CUENTA AS CUENTA,
    CUENTAS.CONCEPTO,
    CUENTAS.IMPORTE
FROM GRUPOS_3 AS GRUPOS
INNER JOIN IMPORTES_CUENTAS_BSEG_5200_3 AS CUENTAS
ON CUENTAS.ID_GRUPO_3 = GRUPOS.ID
WHERE GRUPOS.ID IN ('51000000')
--------------------------------------------------------
UNION ALL
--------------------------------------------------------
SELECT 
    GRUPOS.ID AS ID,
    GRUPOS.SUPERCONCEPTO AS SUPERCONCEPTO,
    CUENTAS.CUENTA AS CUENTA,
    CUENTAS.CONCEPTO,
    CUENTAS.IMPORTE
FROM GRUPOS_4 AS GRUPOS
INNER JOIN IMPORTES_CUENTAS_BSEG_5200_4 AS CUENTAS
ON CUENTAS.ID_GRUPO_4 = GRUPOS.ID
WHERE GRUPOS.ID IN ('50850000')
DISTRIBUTE ON RANDOM;
ALTER TABLE EJEMPLOS 
ORGANIZE ON (ID,CUENTA);