---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 1 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_1 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_1
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_1,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_1 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 2 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_2 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_2
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_2,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_2 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 3 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_3 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_3
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_3,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_3 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 4 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_4 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_4
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_4,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_4 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 5 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_5 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_5
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_5,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_5 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 6 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_6 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_6
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_6,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_6 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 8 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_7 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_7
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_7,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_7 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 8 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_8 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_8
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_8,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_8 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);

---------------------------------------------------
------- TOTALES POR NIVEL DE CUENTA 9 -------------
---------------------------------------------------
DROP TABLE IMPORTES_CUENTAS_BSEG_5200_9 IF EXISTS;
CREATE TABLE IMPORTES_CUENTAS_BSEG_5200_9
AS
SELECT 
    CUENTAS.INDICE,
    CUENTAS.ID_GRUPO_9,
    CUENTAS.CUENTA,
    CUENTAS.CONCEPTO,
    IMPORTES.IMPORTE
FROM CUENTAS_9 AS CUENTAS
LEFT JOIN 
AGREGADOS_CUENTAS_BSEG_5200 AS IMPORTES
ON CUENTAS.CUENTA = IMPORTES.CUENTA
ORDER BY INDICE
DISTRIBUTE ON (CUENTA);
